
services:
  movie_service:
    build: ./movie_service
    command: "uvicorn app.main:app --reload --host 0.0.0.0 --port 8001"
    volumes:
      - ./movie_service:/app
    ports:
      - "8001:8001"
  
  cast_service:
    build: ./cast_service
    command: "uvicorn app.main:app --reload --host 0.0.0.0 --port 8002"
    volumes:
      - ./cast_service:/app
    ports:
      - "8002:8002"
    
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cast_service
      - movie_service
    restart: always
